version: "3"

services:
  uttt:
    image: uttt
    container_name: uttt
    restart: unless-stopped
    build:
      context: ..
      dockerfile: deploy/Dockerfile

    ports:
      - 5000:5000

    environment:
      IN_DOCKER: "TRUE"

    depends_on:
      - redis

  redis:
    image: redis:alpine
